---
# tasks file for molecule-validate-nova-deploy
- name: Set the rpc-openstack variables
  set_fact:
    rpc_openstack: "{{ ansible_local['rpc_openstack']['rpc_product'] }}"
  when:
    - ansible_local.rpc_openstack is defined
    - ansible_local.rpc_openstack.rpc_product is defined
- name: Set the rpc-release variable
  set_fact:
    rpc_product_release: "{{ rpc_openstack['rpc_product_release'] }}"
  when:
    - rpc_openstack is defined
    - rpc_openstack['rpc_product_release'] is defined
    - rpc_product_release is undefined or
      rpc_product_release == 'undefined'
- name: Set the rpc-release variable from environment
  set_fact:
    rpc_product_release: "{{ lookup('env', 'RPC_PRODUCT_RELEASE') }}"
  when:
    - rpc_openstack is undefined or
      rpc_openstack['rpc_product_release'] is undefined

- block:
    - import_tasks: cloning_openstack_ansible_ops.yml
    - import_tasks: create_virtualenv_on_sut.yml
    - import_tasks: run_openstack_service_setup_playbook.yml

  when: ansible_local.service_setup is not defined

- import_tasks: server_delete.yml
